
CREATE TABLE User (
idUser		INTEGER PRIMARY KEY AUTOINCREMENT,
user		TEXT UNIQUE NOT NULL,
name		TEXT NOT NULL,
email		TEXT UNIQUE NOT NULL,
password 	TEXT NOT NULL
);


CREATE TABLE Poll(
idPoll		INTEGER PRIMARY KEY AUTOINCREMENT,
idUser		INTEGER REFERENCES User(idUser) NOT NULL,
name 		TEXT NOT NULL
);

CREATE TABLE Question(
idQuestion		INTEGER PRIMARY KEY AUTOINCREMENT,
idPoll			INTEGER REFERENCES Poll(idPoll) NOT NULL,
qText 			TEXT NOT NULL
);

CREATE TABLE Answer(
idAnswer		INTEGER PRIMARY KEY AUTOINCREMENT,
idQuestion		INTEGER REFERENCES Question(idQuestion) NOT NULL,
qText 			TEXT NOT NULL
);
